.PHONY: clean All

All:
	@echo "----------Building project:[ MixedExpression - Debug ]----------"
	@cd "MixedExpression" && "$(MAKE)" -f  "MixedExpression.mk"
clean:
	@echo "----------Cleaning project:[ MixedExpression - Debug ]----------"
	@cd "MixedExpression" && "$(MAKE)" -f  "MixedExpression.mk" clean
