.PHONY: clean All

All:
	@echo "----------Building project:[ ExpressionAndConversion - Debug ]----------"
	@cd "ExpressionAndConversion" && "$(MAKE)" -f  "ExpressionAndConversion.mk"
clean:
	@echo "----------Cleaning project:[ ExpressionAndConversion - Debug ]----------"
	@cd "ExpressionAndConversion" && "$(MAKE)" -f  "ExpressionAndConversion.mk" clean
